#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path


LOG_WARNING_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    ("overfull", re.compile(r"Overfull \\hbox .*")),
    ("underfull", re.compile(r"Underfull \\hbox .*")),
    ("latex-warning", re.compile(r"LaTeX Warning: .*")),
    ("package-warning", re.compile(r"Package .* Warning: .*")),
]
HIGH_SIGNAL_KEYWORDS = {
    "float-placement": "float specifier changed",
    "float-too-large": "Float too large",
    "undefined-reference": "undefined references",
    "undefined-citation": "undefined citations",
    "rerun-required": "Rerun to get",
    "missing-character": "Missing character:",
}


def require_command(name: str) -> str:
    path = shutil.which(name)
    if not path:
        raise RuntimeError(f"Missing required command: {name}")
    return path


def load_section_paths(report_dir: Path) -> list[Path]:
    section_dir = report_dir / "sections"
    files = sorted(section_dir.glob("*.tex"))
    if not files:
        raise RuntimeError(f"No section files found in {section_dir}")
    return files


def build_section_order(report_dir: Path) -> Path:
    lines = ["% Auto-generated by render_report.py", ""]
    for path in load_section_paths(report_dir):
        lines.append(f"\\input{{sections/{path.stem}.tex}}")
    lines.append("")
    output = report_dir / "build" / "section-order.tex"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines))
    return output


def _read_braced_argument(source: str, start: int) -> tuple[str, int] | None:
    cursor = start
    while cursor < len(source) and source[cursor].isspace():
        cursor += 1
    if cursor >= len(source) or source[cursor] != "{":
        return None

    depth = 0
    chars: list[str] = []
    cursor += 1
    while cursor < len(source):
        char = source[cursor]
        if char == "\\":
            if cursor + 1 < len(source):
                chars.append(char)
                cursor += 1
                chars.append(source[cursor])
                cursor += 1
                continue
        if char == "{":
            depth += 1
            chars.append(char)
            cursor += 1
            continue
        if char == "}":
            if depth == 0:
                return "".join(chars), cursor + 1
            depth -= 1
            chars.append(char)
            cursor += 1
            continue
        chars.append(char)
        cursor += 1
    return None


def _read_bracket_argument(source: str, start: int) -> tuple[str, int] | None:
    cursor = start
    while cursor < len(source) and source[cursor].isspace():
        cursor += 1
    if cursor >= len(source) or source[cursor] != "[":
        return None

    chars: list[str] = []
    cursor += 1
    while cursor < len(source):
        char = source[cursor]
        if char == "\\" and cursor + 1 < len(source):
            chars.append(char)
            cursor += 1
            chars.append(source[cursor])
            cursor += 1
            continue
        if char == "]":
            return "".join(chars), cursor + 1
        chars.append(char)
        cursor += 1
    return None


def _replace_command(
    text: str,
    command: str,
    arg_count: int,
    replacement: Callable[[list[str]], str],
    *,
    allow_star: bool = True,
) -> str:
    needle = f"\\{command}"
    pieces: list[str] = []
    cursor = 0
    while cursor < len(text):
        index = text.find(needle, cursor)
        if index == -1:
            pieces.append(text[cursor:])
            break
        after_name = index + len(needle)
        if after_name < len(text) and (text[after_name].isalpha() or text[after_name] == "@"):
            pieces.append(text[cursor : after_name])
            cursor = after_name
            continue

        arg_cursor = after_name
        if allow_star and arg_cursor < len(text) and text[arg_cursor] == "*":
            arg_cursor += 1

        args: list[str] = []
        for _ in range(arg_count):
            parsed = _read_braced_argument(text, arg_cursor)
            if parsed is None:
                args = []
                break
            arg, arg_cursor = parsed
            args.append(arg)
        if len(args) != arg_count:
            pieces.append(text[cursor : after_name])
            cursor = after_name
            continue

        pieces.append(text[cursor:index])
        pieces.append(replacement(args))
        cursor = arg_cursor
    return "".join(pieces)


def _strip_latex_comments(text: str) -> str:
    cleaned: list[str] = []
    for line in text.splitlines():
        cut_at = len(line)
        for index, char in enumerate(line):
            if char != "%":
                continue
            slash_count = 0
            cursor = index - 1
            while cursor >= 0 and line[cursor] == "\\":
                slash_count += 1
                cursor -= 1
            if slash_count % 2 == 0:
                cut_at = index
                break
        cleaned.append(line[:cut_at])
    return "\n".join(cleaned)


def _normalize_inline(text: str) -> str:
    text = text.replace("~~", "__REPORT_STRIKE__")
    text = text.replace("\\&", "&")
    text = text.replace("\\%", "%")
    text = text.replace("\\_", "_")
    text = text.replace("\\#", "#")
    text = text.replace("\\$", "$")
    text = text.replace("\\{", "{")
    text = text.replace("\\}", "}")
    text = text.replace("~", " ")
    text = text.replace("__REPORT_STRIKE__", "~~")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def _convert_simple_commands(text: str) -> str:
    for command, marker in (("textbf", "**"), ("strong", "**")):
        text = _replace_command(text, command, 1, lambda args, marker=marker: f"{marker}{args[0]}{marker}")
    for command, marker in (("emph", "*"), ("textit", "*")):
        text = _replace_command(text, command, 1, lambda args, marker=marker: f"{marker}{args[0]}{marker}")
    text = _replace_command(text, "texttt", 1, lambda args: f"`{_normalize_inline(args[0])}`")
    text = _replace_command(text, "url", 1, lambda args: f"<{_normalize_inline(args[0])}>")
    text = _replace_command(
        text,
        "href",
        2,
        lambda args: f"[{_normalize_inline(args[1])}]({_normalize_inline(args[0])})",
    )
    text = _replace_command(text, "cref", 1, lambda args: f"图/表 {_normalize_inline(args[0])}")
    text = _replace_command(text, "Cref", 1, lambda args: f"图/表 {_normalize_inline(args[0])}")
    text = _replace_command(text, "ref", 1, lambda args: f"图/表 {_normalize_inline(args[0])}")
    text = _replace_command(text, "cite", 1, lambda args: f"[cite: {_normalize_inline(args[0])}]")
    text = _replace_command(text, "label", 1, lambda _args: "")
    text = _replace_command(text, "rptlabel", 1, lambda args: f"**{_normalize_inline(args[0])}**")
    text = _replace_command(text, "caption", 1, lambda args: f"\n\n**图/表：{_normalize_inline(args[0])}**\n\n")
    text = _replace_command(text, "input", 1, lambda args: f"\n\n> 图源：`{_normalize_inline(args[0])}`\n\n")
    return text


def _convert_diff_macros(text: str) -> str:
    text = _replace_command(text, "reportchg", 2, lambda args: f"~~{args[0]}~~ **{args[1]}**")
    text = _replace_command(text, "reportadd", 1, lambda args: f"**{args[0]}**")
    text = _replace_command(text, "reportdel", 1, lambda args: f"~~{args[0]}~~")
    return text


def _convert_headings(text: str) -> str:
    heading_levels = [
        ("chapter", "##"),
        ("section", "##"),
        ("subsection", "###"),
        ("subsubsection", "####"),
        ("paragraph", "#####"),
    ]
    for command, marker in heading_levels:
        text = _replace_command(
            text,
            command,
            1,
            lambda args, marker=marker: f"\n\n{marker} {_normalize_inline(_convert_simple_commands(args[0]))}\n\n",
        )
    return text


def _convert_list_environment(text: str, environment: str, ordered: bool) -> str:
    pattern = re.compile(rf"\\begin\{{{environment}\}}(.*?)\\end\{{{environment}\}}", re.DOTALL)

    def replace(match: re.Match[str]) -> str:
        body = match.group(1)
        raw_items = re.split(r"\\item(?:\[[^\]]+\])?\s*", body)
        items = [item for item in raw_items[1:] if item.strip()]
        lines: list[str] = []
        for index, item in enumerate(items, start=1):
            item_text = _normalize_inline(latex_to_markdown(item))
            if not item_text:
                continue
            marker = f"{index}." if ordered else "-"
            lines.append(f"{marker} {item_text}")
        return "\n\n" + "\n".join(lines) + "\n\n"

    return pattern.sub(replace, text)


def _convert_description_environment(text: str) -> str:
    pattern = re.compile(r"\\begin\{description\}(.*?)\\end\{description\}", re.DOTALL)

    def replace(match: re.Match[str]) -> str:
        body = match.group(1)
        item_pattern = re.compile(r"\\item\[(.*?)\]\s*(.*?)(?=\\item\[|\Z)", re.DOTALL)
        lines: list[str] = []
        for item_match in item_pattern.finditer(body):
            term = _normalize_inline(latex_to_markdown(item_match.group(1)))
            detail = _normalize_inline(latex_to_markdown(item_match.group(2)))
            lines.append(f"- **{term}**: {detail}" if detail else f"- **{term}**")
        return "\n\n" + "\n".join(lines) + "\n\n"

    return pattern.sub(replace, text)


def _convert_tabular_body(body: str) -> str:
    body = re.sub(r"\\(?:toprule|midrule|bottomrule|hline)\b", "", body)
    body = re.sub(r"\\noalign\s*\{[^{}]*\}", "", body)
    body = re.sub(r"\\(?:endfirsthead|endhead|endfoot|endlastfoot)\b", "", body)
    rows: list[list[str]] = []
    for raw_row in re.split(r"\\\\", body):
        row = raw_row.strip()
        if not row:
            continue
        row = re.sub(r"\\multicolumn\{[^{}]*\}\{[^{}]*\}\{([^{}]*)\}", r"\1", row)
        cells = [_normalize_inline(latex_to_markdown(cell)) for cell in row.split("&")]
        cells = [cell for cell in cells if cell]
        if cells:
            rows.append(cells)
    if not rows:
        return ""

    width = max(len(row) for row in rows)
    normalized_rows = [row + [""] * (width - len(row)) for row in rows]
    header = normalized_rows[0]
    separator = ["---"] * width
    markdown_rows = [
        "| " + " | ".join(header) + " |",
        "| " + " | ".join(separator) + " |",
    ]
    for row in normalized_rows[1:]:
        markdown_rows.append("| " + " | ".join(row) + " |")
    return "\n\n" + "\n".join(markdown_rows) + "\n\n"


def _convert_tabular_environments(text: str) -> str:
    begin_pattern = re.compile(r"\\begin\{(?P<env>tabularx|xltabular|tabular|longtable)\}")
    pieces: list[str] = []
    cursor = 0
    while True:
        match = begin_pattern.search(text, cursor)
        if not match:
            pieces.append(text[cursor:])
            break

        environment = match.group("env")
        end_marker = f"\\end{{{environment}}}"
        end_index = text.find(end_marker, match.end())
        if end_index == -1:
            pieces.append(text[cursor:])
            break

        body_start = match.end()
        for _ in range(4):
            bracket_arg = _read_bracket_argument(text, body_start)
            if bracket_arg is not None:
                _arg, body_start = bracket_arg
                continue
            parsed = _read_braced_argument(text, body_start)
            if parsed is None:
                break
            _arg, body_start = parsed

        body = text[body_start:end_index]
        pieces.append(text[cursor : match.start()])
        pieces.append(_convert_tabular_body(body))
        cursor = end_index + len(end_marker)
    return "".join(pieces)


def _convert_tikz_environments(text: str) -> str:
    pattern = re.compile(r"\\begin\{tikzpicture\}(?:\[[^\]]*\])?.*?\\end\{tikzpicture\}", re.DOTALL)
    return pattern.sub("\n\n> TikZ 图源保留在 LaTeX 真源中。\n\n", text)


def _remove_environment_wrappers(text: str) -> str:
    for environment in ("table", "table*", "figure", "figure*", "center"):
        escaped = re.escape(environment)
        text = re.sub(rf"\\begin\{{{escaped}\}}(?:\[[^\]]*\])?", "\n\n", text)
        text = re.sub(rf"\\end\{{{escaped}\}}", "\n\n", text)
    return text


def _cleanup_markdown(text: str) -> str:
    text = re.sub(r"\\(?:centering|noindent|small|footnotesize|scriptsize|normalsize)\b", "", text)
    text = re.sub(r"\\(?:vspace|hspace)\*?\{[^{}]*\}", "", text)
    text = re.sub(r"\\begin\{[^{}]*\}", "", text)
    text = re.sub(r"\\end\{[^{}]*\}", "", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    cleaned_lines: list[str] = []
    for line in text.splitlines():
        stripped = _normalize_inline(line) if not line.startswith(("#", "|", "-", ">", "1.")) else line.rstrip()
        if stripped or (cleaned_lines and cleaned_lines[-1]):
            cleaned_lines.append(stripped)
    return "\n".join(cleaned_lines).strip() + "\n"


def latex_to_markdown(source: str) -> str:
    """Convert the report family's common LaTeX subset into Markdown."""
    text = source.replace("\r\n", "\n")
    text = _strip_latex_comments(text)
    text = _convert_diff_macros(text)
    text = _convert_headings(text)
    text = _convert_description_environment(text)
    text = _convert_list_environment(text, "itemize", ordered=False)
    text = _convert_list_environment(text, "enumerate", ordered=True)
    text = _remove_environment_wrappers(text)
    text = _convert_tikz_environments(text)
    text = _convert_tabular_environments(text)
    text = _convert_simple_commands(text)
    text = text.replace("\\(", "$").replace("\\)", "$")
    text = text.replace("\\[", "\n\n$$\n").replace("\\]", "\n$$\n\n")
    return _cleanup_markdown(text)


def _read_yaml_scalar(path: Path, key: str) -> str | None:
    if not path.exists():
        return None
    pattern = re.compile(rf"^{re.escape(key)}:\s*(.*?)\s*$")
    for line in path.read_text(errors="ignore").splitlines():
        match = pattern.match(line)
        if not match:
            continue
        value = match.group(1).strip()
        if not value:
            return None
        if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
            value = value[1:-1]
        return value
    return None


def read_report_title(report_dir: Path) -> str:
    return (
        _read_yaml_scalar(report_dir / "metadata.yaml", "title")
        or _read_yaml_scalar(report_dir / "brief.yaml", "title")
        or report_dir.name
    )


def export_markdown(report_dir: Path, output_path: Path) -> Path:
    title = read_report_title(report_dir)
    lines = [
        f"# {title}",
        "",
        "> 本文件由 `render_report.py` 从 LaTeX 真源自动生成；请修改报告工作区的 `sections/*.tex` 后重新渲染。",
        "",
    ]
    for section_path in load_section_paths(report_dir):
        converted = latex_to_markdown(section_path.read_text())
        if converted.strip():
            lines.append(converted.strip())
            lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines).strip() + "\n")
    return output_path


def run_xelatex(report_dir: Path, main_tex: Path) -> subprocess.CompletedProcess[str]:
    xelatex = require_command("xelatex")
    cmd = [
        xelatex,
        "-interaction=nonstopmode",
        "-halt-on-error",
        "-file-line-error",
        "-output-directory",
        "build",
        main_tex.name,
    ]
    return subprocess.run(cmd, cwd=report_dir, capture_output=True, text=True)


def review_log(report_dir: Path) -> list[str]:
    log_path = report_dir / "build" / "main.log"
    if not log_path.exists():
        return ["[WARN] Missing build/main.log, compile review was incomplete."]

    findings: list[str] = []
    seen: set[str] = set()
    for raw_line in log_path.read_text(errors="ignore").splitlines():
        line = " ".join(raw_line.split())
        if not line:
            continue
        lowered = line.lower()
        matched = False
        for label, pattern in LOG_WARNING_PATTERNS:
            if pattern.search(raw_line):
                findings.append(f"[WARN] {label}: {line}")
                matched = True
                break
        if matched:
            continue
        for label, marker in HIGH_SIGNAL_KEYWORDS.items():
            if marker.lower() in lowered:
                findings.append(f"[WARN] {label}: {line}")
                break

    deduped: list[str] = []
    for item in findings:
        if item in seen:
            continue
        seen.add(item)
        deduped.append(item)
    return deduped


def write_compile_review(
    report_dir: Path,
    findings: list[str],
    output_path: Path,
    markdown_output_path: Path | None = None,
) -> Path:
    review_path = report_dir / "build" / "compile-review.md"
    lines = [
        "# Compile Review",
        "",
        f"- 报告工作区: `{report_dir}`",
        f"- 输出 PDF: `{output_path}`",
        *([f"- 输出 Markdown: `{markdown_output_path}`"] if markdown_output_path else []),
        f"- 自检报告: `{report_dir / 'build' / 'self-check.md'}`",
        "",
        "## 编译审查结论",
        "",
    ]

    if not findings:
        lines.append("- 未检测到编译 warning。")
    else:
        lines.append("- 本次编译已完成，但存在必须清理的 warning；这不是可发布状态。")

    lines.extend(["", "## 编译警告", ""])
    if findings:
        lines.extend(f"- {item}" for item in findings)
    else:
        lines.append("- 无。")

    lines.extend(
        [
            "",
            "## 审查动作建议",
            "",
            "- 优先处理 overfull / underfull、表格过宽、浮动体位置异常、未定义引用与 citation。",
            "- 若清理 warning 需要改变表格布局、图表位置或结论强调，应先问用户“怎么改”；不要把 warning 本身当作可发布状态。",
            "- 查看 `build/self-check.md`，确认结构、风格、术语与 `项目进度` 章节也通过检查。",
            "",
        ]
    )
    review_path.write_text("\n".join(lines))
    return review_path


def run_self_check(report_dir: Path) -> Path | None:
    script_path = Path(__file__).resolve().with_name("self_check_report.py")
    if not script_path.exists():
        return None
    cmd = [sys.executable, str(script_path), str(report_dir)]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip() or "self_check_report.py failed.")
    return report_dir / "build" / "self-check.md"


def render_pdf(report_dir: Path, output_path: Path) -> list[str]:
    main_tex = report_dir / "main.tex"
    if not main_tex.exists():
        raise RuntimeError(f"Missing main.tex: {main_tex}")
    if not (report_dir / "style.tex").exists():
        raise RuntimeError(f"Missing style.tex: {report_dir / 'style.tex'}")

    build_section_order(report_dir)

    for pass_index in range(1, 4):
        result = run_xelatex(report_dir, main_tex)
        if result.returncode != 0:
            raise RuntimeError(
                result.stderr.strip()
                or result.stdout.strip()
                or f"XeLaTeX pass {pass_index} failed."
            )

    pdf_path = report_dir / "build" / "main.pdf"
    if not pdf_path.exists():
        raise RuntimeError(f"Expected PDF not found: {pdf_path}")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(pdf_path, output_path)
    return review_log(report_dir)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render a LaTeX report workspace to PDF plus Markdown and review compile warnings.")
    parser.add_argument("report_dir", help="Path to the report workspace.")
    parser.add_argument("--output", help="Optional output PDF path. Default: docs/report/report.pdf in the standard layout.")
    parser.add_argument(
        "--markdown-output",
        help="Optional output Markdown path. Default: docs/report/report.md in the standard layout.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    report_dir = Path(args.report_dir).resolve()
    if not report_dir.exists():
        print(f"[ERROR] Report workspace not found: {report_dir}")
        return 1

    output_path = Path(args.output).resolve() if args.output else report_dir.parent / "report.pdf"
    markdown_output_path = (
        Path(args.markdown_output).resolve() if args.markdown_output else report_dir.parent / "report.md"
    )

    try:
        compile_findings = render_pdf(report_dir, output_path)
        export_markdown(report_dir, markdown_output_path)
    except Exception as exc:
        print(f"[ERROR] {exc}")
        return 1

    review_path = write_compile_review(report_dir, compile_findings, output_path, markdown_output_path)
    try:
        self_check_path = run_self_check(report_dir)
    except Exception as exc:
        print(f"[ERROR] {exc}")
        return 1

    for finding in compile_findings:
        print(finding)

    if compile_findings:
        print("[ERROR] Compile warnings must be cleared before treating the report as complete.")
        return 1

    print("[OK] Rendered PDF with no compile warnings detected in build/main.log.")
    print(f"[OK] Wrote compile review: {review_path}")
    if self_check_path:
        print(f"[OK] Wrote self check: {self_check_path}")
    print(f"[OK] Rendered PDF: {output_path}")
    print(f"[OK] Rendered Markdown: {markdown_output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
